[package]
name = "frontier-template-runtime"
version = "0.0.0"
authors = ["Substrate DevHub <https://github.com/substrate-developer-hub>"]
edition = "2021"
license = "Unlicense"
homepage = "https://substrate.io"
repository = "https://github.com/substrate-developer-hub/frontier-node-template/"
publish = false

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
serde = { version = "1.0.101", features = ["derive"], optional = true }

codec = { package = "parity-scale-codec", version = "3.0.0", default-features = false, features = ["derive"] }
scale-info = { version = "2.0.0", default-features = false, features = ["derive"] }
sp-api = { version = "4.0.0-dev", git = "https://github.com/woozzzzy/sh", default-features = false , branch = "polkadot-v0.9.19" }
sp-block-builder = { version = "4.0.0-dev", git = "https://github.com/woozzzzy/sh", default-features = false , branch = "polkadot-v0.9.19" }
sp-consensus-aura = { version = "0.10.0-dev", git = "https://github.com/woozzzzy/sh", default-features = false , branch = "polkadot-v0.9.19" }
sp-core = { version = "6.0.0", git = "https://github.com/woozzzzy/sh", default-features = false , branch = "polkadot-v0.9.19" }
sp-inherents = { version = "4.0.0-dev", git = "https://github.com/woozzzzy/sh", default-features = false , branch = "polkadot-v0.9.19" }
sp-io = { version = "6.0.0", git = "https://github.com/woozzzzy/sh", default-features = false , branch = "polkadot-v0.9.19" }
sp-offchain = { version = "4.0.0-dev", git = "https://github.com/woozzzzy/sh", default-features = false , branch = "polkadot-v0.9.19" }
sp-runtime = { version = "6.0.0", git = "https://github.com/woozzzzy/sh", default-features = false , branch = "polkadot-v0.9.19" }
sp-session = { version = "4.0.0-dev", git = "https://github.com/woozzzzy/sh", default-features = false , branch = "polkadot-v0.9.19" }
sp-std = { version = "4.0.0", git = "https://github.com/woozzzzy/sh", default-features = false , branch = "polkadot-v0.9.19" }
sp-transaction-pool = { version = "4.0.0-dev", git = "https://github.com/woozzzzy/sh", default-features = false , branch = "polkadot-v0.9.19" }
sp-version = { version = "5.0.0", git = "https://github.com/woozzzzy/sh", default-features = false , branch = "polkadot-v0.9.19" }

frame-executive = { version = "4.0.0-dev", git = "https://github.com/woozzzzy/sh", default-features = false , branch = "polkadot-v0.9.19" }
frame-support = { version = "4.0.0-dev", git = "https://github.com/woozzzzy/sh", default-features = false , branch = "polkadot-v0.9.19" }
frame-system = { version = "4.0.0-dev", git = "https://github.com/woozzzzy/sh", default-features = false , branch = "polkadot-v0.9.19" }
frame-system-rpc-runtime-api = { version = "4.0.0-dev", git = "https://github.com/woozzzzy/sh", default-features = false , branch = "polkadot-v0.9.19" }
pallet-aura = { version = "4.0.0-dev", git = "https://github.com/woozzzzy/sh", default-features = false , branch = "polkadot-v0.9.19" }
pallet-balances = { version = "4.0.0-dev", git = "https://github.com/woozzzzy/sh", default-features = false , branch = "polkadot-v0.9.19" }
pallet-grandpa = { version = "4.0.0-dev", git = "https://github.com/woozzzzy/sh", default-features = false , branch = "polkadot-v0.9.19" }
pallet-randomness-collective-flip = { version = "4.0.0-dev", git = "https://github.com/woozzzzy/sh", default-features = false , branch = "polkadot-v0.9.19" }
pallet-sudo = { version = "4.0.0-dev", git = "https://github.com/woozzzzy/sh", default-features = false , branch = "polkadot-v0.9.19" }
pallet-timestamp = { version = "4.0.0-dev", git = "https://github.com/woozzzzy/sh", default-features = false , branch = "polkadot-v0.9.19" }
pallet-transaction-payment = { version = "4.0.0-dev", git = "https://github.com/woozzzzy/sh", default-features = false , branch = "polkadot-v0.9.19" }
pallet-transaction-payment-rpc-runtime-api = { version = "4.0.0-dev", git = "https://github.com/woozzzzy/sh", default-features = false , branch = "polkadot-v0.9.19" }
# benchmarking dependencies
frame-benchmarking = { version = "4.0.0-dev", git = "https://github.com/woozzzzy/sh", default-features = false, optional = true , branch = "polkadot-v0.9.19" }
frame-system-benchmarking = { version = "4.0.0-dev", git = "https://github.com/woozzzzy/sh", default-features = false, optional = true , branch = "polkadot-v0.9.19" }

fp-rpc = { path = "../../primitives/rpc", default-features = false }
fp-self-contained = { path = "../../primitives/self-contained", default-features = false }

pallet-base-fee = { path = "../../frame/base-fee", default-features = false }
pallet-dynamic-fee = { path = "../../frame/dynamic-fee", default-features = false }
pallet-ethereum = { path = "../../frame/ethereum", default-features = false }
pallet-evm = { path = "../../frame/evm", default-features = false }
pallet-evm-precompile-modexp = { path = "../../frame/evm/precompile/modexp", default-features = false }
pallet-evm-precompile-sha3fips = { path = "../../frame/evm/precompile/sha3fips", default-features = false }
pallet-evm-precompile-simple = { path = "../../frame/evm/precompile/simple", default-features = false }

[build-dependencies]
substrate-wasm-builder = { version = "5.0.0-dev", git = "https://github.com/woozzzzy/sh", branch = "polkadot-v0.9.19" }

[features]
default = ["std", "aura", "with-rocksdb-weights"]
aura = []
manual-seal = ["with-rocksdb-weights"]
with-rocksdb-weights = []
with-paritydb-weights = []
std = [
	"serde",

	"codec/std",
	"scale-info/std",
	"sp-api/std",
	"sp-block-builder/std",
	"sp-consensus-aura/std",
	"sp-core/std",
	"sp-inherents/std",
	"sp-io/std",
	"sp-offchain/std",
	"sp-runtime/std",
	"sp-session/std",
	"sp-std/std",
	"sp-transaction-pool/std",
	"sp-version/std",

	"frame-executive/std",
	"frame-support/std",
	"frame-system-rpc-runtime-api/std",
	"frame-system/std",
	"pallet-aura/std",
	"pallet-balances/std",
	"pallet-grandpa/std",
	"pallet-randomness-collective-flip/std",
	"pallet-sudo/std",
	"pallet-timestamp/std",
	"pallet-transaction-payment-rpc-runtime-api/std",
	"pallet-transaction-payment/std",

	"fp-rpc/std",
	"fp-self-contained/std",

	"pallet-base-fee/std",
	"pallet-dynamic-fee/std",
	"pallet-ethereum/std",
	"pallet-evm/std",
	"pallet-evm-precompile-simple/std",
	"pallet-evm-precompile-sha3fips/std",
]
runtime-benchmarks = [
	"frame-benchmarking",
	"frame-system-benchmarking",
	"frame-system/runtime-benchmarks",
	"pallet-ethereum/runtime-benchmarks",
	"pallet-evm/runtime-benchmarks",
]
