[package]
name = "fp-consensus"
version = "2.0.0-dev"
authors = ["Parity Technologies <admin@parity.io>"]
description = "Primitives for Frontier consensus"
edition = "2021"
license = "Apache-2.0"
homepage = "https://substrate.io"
repository = "https://github.com/paritytech/frontier/"

[dependencies]
ethereum = { version = "0.12.0", default-features = false, features = ["with-codec"] }

codec = { package = "parity-scale-codec", version = "3.0.0", default-features = false, features = ["derive"] }
sp-core = { version = "6.0.0", git = "https://github.com/woozzzzy/sh", default-features = false , branch = "polkadot-v0.9.19" }
sp-runtime = { version = "6.0.0", git = "https://github.com/woozzzzy/sh", default-features = false , branch = "polkadot-v0.9.19" }
sp-std = { version = "4.0.0", git = "https://github.com/woozzzzy/sh", default-features = false , branch = "polkadot-v0.9.19" }

[features]
default = ["std"]
std = [
	"ethereum/std",

	"codec/std",
	"sp-core/std",
	"sp-runtime/std",
	"sp-std/std",
]
